# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

version: "3.8"
services:
  toonami-downlink:
    build: .
    image: toonami-downlink:latest
    container_name: toonami-downlink
    ports:
      - "7004:7004"
    volumes:
      - /mnt/user/appdata/toonami-downlink:/data
    environment:
      - CRON_SCHEDULE=0 3 * * *
      - ALLOW_ANONYMOUS_LOCAL_REFRESH=true
    restart: unless-stopped
